import { z } from 'zod';

export const PatientDetailsSchema = z.object({
  patientId: z.string().optional(),
  firstName: z.string().min(1, 'First name is required'),
  lastName: z.string().min(1, 'Last name is required'),
  fullNameHi: z.string().optional(),
  dateOfBirth: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'Invalid date format'),
  gender: z.enum(['male', 'female', 'other']),
  address: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  country: z.string().default('India'),
  zipCode: z.string().optional(),
  phone: z.string().optional(),
  email: z.string().email().optional(),
  bloodGroup: z.string().optional(),
  assignedDoctor: z.string().optional(),
  department: z.string().optional(),
  admissionDate: z.string().optional(),
  patientType: z.string().default('outpatient'),
  medicalConditions: z.array(z.string()).default([]),
  allergies: z.array(z.string()).default([]),
  medications: z.array(z.string()).default([]),
  emergencyName: z.string().optional(),
  emergencyRelation: z.string().optional(),
  emergencyPhone: z.string().optional(),
  insuranceProvider: z.string().optional(),
  insurancePolicyNumber: z.string().optional(),
  validUntil: z.string().optional(),
  insuranceGroupNumber: z.string().optional(),
  status: z.string().default('active'),
});